platform: x64
configuration: Release
image: Visual Studio 2017

environment:
  matrix:
    - PYTHON: "C:\\Python27-x64"

install:
 - set PATH=%PYTHON%\Scripts;%PYTHON%;%PATH%
 - python -m pip install --upgrade pip
 - pip install -U rosdep rosinstall_generator wstool rosinstall
 - pip install -U --force-reinstall --no-deps -r 'https://ros-win.visualstudio.com/defaultcollection/ros-win/_apis/git/repositories/ros-win/items?api-version=1.0&scopepath=%2Ftools%2Fcatkin-requirements.patch.txt'
 - pip freeze

build_script:
 - dir